config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/questionnaire', to: 'pages#questionnaire'
  patch '/users/update', to: 'users#update'
end

app/models/examiner.rb
class Examiner

	attr_reader :user

	def self.prepare_for(user)
		examiner = new(user)
		examiner.examine!
	end

	def initialize(user)
		@user = user
	end

	def examine!
		record = @user.records.create
		binary_array = @user.binary_array
		binary_array.each_with_index do |bit, uid|
			result = translate(bit,uid)
			record.update!(result)
		end
		record.calculate_type!
	end

	def translate(bit,uid)
		if question = Question.find_by(uid: uid)
			case
				when bit < 0 then { type: question.result_a[0], score: (question.result_a[1].to_i * bit).abs }
				when bit > 0 then { type: question.result_b[0], score: (question.result_b[1].to_i * bit).abs }
				else nil
			end
		end
	end

end

app/models/personality_type.rb
class PersonalityType < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base

	def translate(bit,uid)
		if question = Question.find_by(uid: uid)
			case 
				when bit < 0 then { type: question.result_a[0], score: (question.result_a[1].to_i * bit).abs }
				when bit > 0 then { type: question.result_b[0], score: (question.result_b[1].to_i * bit).abs }
				else nil
			end 
		end 
	end

end

app/models/questionnaire.rb
class Questionnaire

	def self.create_full_for(user)
    Question.all
	end

  def self.create_partial_for(user)
    Question.all.shuffle.first(10)
  end

end

app/models/record.rb
class Record < ActiveRecord::Base

	has_one :personality_type

	def update!(result)
		unless result.nil?
			case result[:type]
				when "E" then self.EI += result[:score]
				when "I" then self.EI -= result[:score]
				when "S" then self.SN += result[:score]
				when "N" then self.SN -= result[:score]
				when "T" then self.TF += result[:score]
				when "F" then self.TF -= result[:score]
				when "J" then self.JP += result[:score]
				when "P" then self.JP -= result[:score]
			end
		end
		self.save
	end

	def calculate_type!
		personality_type = ""
		self.EI > 0 ? personality_type += "E" : personality_type += "I"
		self.SN > 0 ? personality_type += "S" : personality_type += "N"
		self.TF > 0 ? personality_type += "T" : personality_type += "F"
		self.JP > 0 ? personality_type += "J" : personality_type += "P"
		self.personality_type = PersonalityType.find_by(name: personality_type)
		self.save
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :records, dependent: :destroy

  def binary_array
		binary_string.split('').map { |char| char == "x" ? 4 : char.to_i }.map { |byte| (byte - 4) }
  end

  def questionnaire_complete?
  	self.records.length > 0
  end

  def update_binary_string_with(answers)
    binary_string = ""
    update(binary_string: "")
    answers.each { |uid, score| binary_string << score }
    update(binary_string: binary_string)
  end

  def current_type
    self.records.order(created_at: :desc).first.personality_type
  end

  def ei_history
    output = {}
    self.records.each { |record| output[record.created_at] = record.EI }
    output
  end

  def sn_history
    output = {}
    self.records.each { |record| output[record.created_at] = record.SN }
    output
  end

  def tf_history
    output = {}
    self.records.each { |record| output[record.created_at] = record.TF }
    output
  end

  def jp_history
    output = {}
    self.records.each { |record| output[record.created_at] = record.JP }
    output
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	# before_action :authenticate_user!

	def home
		redirect_to new_user_session_path unless user_signed_in?
	end

	def questionnaire
    if current_user.questionnaire_complete?
      @questionnaire = Questionnaire.create_partial_for(current_user)
    else
  		@questionnaire = Questionnaire.create_full_for(current_user)
    end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	def update
		answers = params[:answers]
		current_user.update_binary_string_with(answers)
		Examiner.prepare_for(current_user)
		@record = current_user.records.last
		redirect_to "/"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evolving Personality</title>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>
</body>

</html>

app/views/pages/home.html.erb
<header>
	<h1>Evolving Personality Alpha</h1>
	<nav>
		<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
	</nav>
</header>

<section id="content">
  <% if current_user.questionnaire_complete? %>
    <%= link_to "Continue Analysis", questionnaire_path %>
    <p>Your current personality type is: <a href='<%= current_user.current_type.url %>'><%= current_user.current_type.name %></a></p>
    <%= line_chart current_user.ei_history, {library: {hAxis: {title: "(+) extraversion / (-) introversion"} } } %>
    <%= line_chart current_user.sn_history, {library: {hAxis: {title: "(+) sensing / (-) intuition"} } } %>
    <%= line_chart current_user.tf_history, {library: {hAxis: {title: "(+) thinking / (-) feeling"} } } %>
    <%= line_chart current_user.jp_history, {library: {hAxis: {title: "(+) judging / (-) perceiving"} } } %>
  <% else %>
    <p id='info'>Welcome to Evolving Personality Alpha. This application graphs the evolution of your personality over time. To start, click "Start Analysis" and answer 48 questions about yourself. It's kinda long, I know, but you only have to do this once. Your answers will be used to determine your Myers-Briggs personality type, and four new points will appear on four new graphs on your front page. Everytime you revisit this site, you'll have the opportunity to answer 10 quick questions, and update these graphs. Have fun tracking the changes in your personality!</p>
  	<%= link_to "Start Analysis", questionnaire_path %>
  <% end %>


</section>

app/views/pages/questionnaire.html.erb
<h1>Questionnaire</h1>

<%= form_tag("/users/update", method: "patch") do %>
	<% @questionnaire.each do |question| %>
		<h2><%= question.prompt %></h2>
		<p><%=question.choice_a%></p><%= range_field(:answers, question.uid, in: 1..7 )%><p><%=question.choice_b%></p>
	<% end %>
  <%= submit_tag("Submit!") %>
<% end %>